branch-defaults:
  default:
    environment: udagram-api-dev
    group_suffix: null
  master:
    environment: udagram-api-dev
    group_suffix: null
deploy:
  artifact: www/Archive.zip
global:
  application_name: udagram-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
